### ISSUE TITLE
我想推一些commit，怎么办？

### ISSUE THREAD

**Issue by gdh1995** [Epsirom/AuthTHU#1]
![image](https://cloud.githubusercontent.com/assets/5547703/12372743/7f4033f4-bc9c-11e5-86bb-f3b342be78ae.png)

主要是修bug

**Comment by Epsirom** [comment]
推呗~~

**Comment by Epsirom** [comment]
pull request发过来吧

**Comment by gdh1995** [comment]
@Epsirom 我没有私有仓库，你给个这仓库的branch的权限？

**Comment by Epsirom** [comment]
现在这个仓库是公开的……
不过图方便还是给你直接加成协作者好了……

**Comment by gdh1995** [comment]
Please see PR #2 .
